openapi: 3.1.0
info:
  title: RAG Chatbot API
  version: 1.0.0
  description: REST API for Physical AI & Humanoid Robotics textbook chatbot

servers:
  - url: http://localhost:8000
    description: Development server

paths:
  /api/chat/query:
    post:
      summary: Submit a chat query
      operationId: submitQuery
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - session_id
                - query
              properties:
                session_id:
                  type: string
                  format: uuid
                  description: Client-generated session identifier
                query:
                  type: string
                  minLength: 1
                  maxLength: 1000
                  description: User's question
                context:
                  type: object
                  properties:
                    current_page:
                      type: string
                      description: Current page URL (e.g., /docs/module-1/chapter-1)
                    selected_text:
                      type: string
                      maxLength: 500
                      description: Text selected by user for context
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  message_id:
                    type: string
                    format: uuid
                  response:
                    type: string
                    description: Markdown-formatted answer
                  citations:
                    type: array
                    items:
                      type: object
                      properties:
                        source:
                          type: string
                          example: "Module 1, Chapter 2"
                        excerpt:
                          type: string
                        relevance:
                          type: number
                          format: float
                          minimum: 0
                          maximum: 1
                  suggested_questions:
                    type: array
                    items:
                      type: string
                  processing_time_ms:
                    type: integer
        '400':
          description: Invalid request
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
        '429':
          description: Rate limit exceeded
          headers:
            Retry-After:
              schema:
                type: integer
              description: Seconds until retry allowed
        '500':
          description: Server error

  /api/chat/history/{session_id}:
    get:
      summary: Retrieve conversation history
      operationId: getHistory
      parameters:
        - name: session_id
          in: path
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: Conversation history
          content:
            application/json:
              schema:
                type: object
                properties:
                  session_id:
                    type: string
                    format: uuid
                  messages:
                    type: array
                    items:
                      type: object
                      properties:
                        role:
                          type: string
                          enum: [user, assistant]
                        content:
                          type: string
                        timestamp:
                          type: string
                          format: date-time
                        citations:
                          type: array
                          items:
                            type: object
        '404':
          description: Session not found

  /health:
    get:
      summary: Health check
      operationId: healthCheck
      responses:
        '200':
          description: Service healthy
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: "healthy"
                  timestamp:
                    type: string
                    format: date-time

  /health/dependencies:
    get:
      summary: Check dependency health
      operationId: dependencyHealth
      responses:
        '200':
          description: Dependency status
          content:
            application/json:
              schema:
                type: object
                properties:
                  qdrant:
                    $ref: '#/components/schemas/ServiceStatus'
                  neon_postgres:
                    $ref: '#/components/schemas/ServiceStatus'
                  openai:
                    $ref: '#/components/schemas/ServiceStatus'

components:
  schemas:
    ServiceStatus:
      type: object
      properties:
        status:
          type: string
          enum: [up, down]
        latency_ms:
          type: integer
